phrase:
  access_token: 078cd499fbeca7535f919866c42feaa2ab00c44edd7b871538cc6a28d3679835
  project_id: 0f4e1eab2a7a81b344181640dfc5d8bc
  file_format: yml
  push:
    sources:
    - file: ./common/src/locales/en.json
      params:
        update_translations: true
        file_format: json
        locale_id: 8c702d7cc05197000271a45a530cccd0
        format_options: react_nested_json
    - file: ./common/src/locales/fr.json
      params:
        update_translations: true
        file_format: json
        locale_id: de52e4472d0c4fdabdfa7f2a8ae744d5
        format_options: react_nested_json
  pull:
    targets:
    - file: ./common/src/locales/en.json
      params:
        file_format: json
        format_options: react_nested_json
    - file: ./common/src/locales/fr.json
      params:
        file_format: json
        format_options: react_nested_json