phrase:
  access_token: 078cd499fbeca7535f919866c42feaa2ab00c44edd7b871538cc6a28d3679835
  project_id: 0f4e1eab2a7a81b344181640dfc5d8bc
  file_format: yml
  push:
    sources:
    - file: ./common/src/locales/en.json
      update_translations: true
      file_format: json
      locale_id: 8c702d7cc05197000271a45a530cccd0
    - file: ./common/src/locales/fr.json
      update_translations: true
      file_format: json
      locale_id: de52e4472d0c4fdabdfa7f2a8ae744d5
  pull:
    targets:
    - file: ./common/src/locales/en.json
      file_format: json
    - file: ./common/src/locales/fr.json
      file_format: json